env                                           = "dev"
region                                        = "us-east-1"
aws_account_number                            = "332281781429"
created_by                                    = "BizCloudExperts"
omnidev_email                                 = "omnidev@bizcloudexperts.com"
omni_noreply_email                            = "no-reply@omnilogistics.com"